# Generated by Django 3.1.4 on 2021-01-04 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(help_text='Enter a Card Infomation (e.g. 개발운영2실', max_length=20)),
                ('card_number', models.CharField(help_text='카드번호', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(4)])),
                ('user_name', models.CharField(max_length=10)),
                ('user_phone', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Chit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_date', models.DateField()),
                ('amount', models.IntegerField(default=0)),
                ('place', models.CharField(help_text='주문장소', max_length=20)),
                ('number_of_user', models.IntegerField()),
                ('list_of_user', models.TextField(help_text='먹은 인원', max_length=500)),
                ('meal_type', models.CharField(choices=[('1', '야근식비'), ('2', '접대비'), ('3', '휴일근무식비')], default='1', help_text='야근식비/접대비/휴일근무식비', max_length=1)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinner.cardinfo')),
                ('order_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dinner.userinfo')),
            ],
            options={
                'ordering': ['base_date', 'card'],
            },
        ),
    ]
